[tool.pylint.main]
# Files or directories to be skipped. They should be base names, not paths.
ignore = [".git",".github"]

[tool.pylint.miscellaneous]
# List of note tags to take in consideration, separated by a comma.
notes = ["FIXME", "DEBUG", "TODO"]
